# Generated by Django 4.2.7 on 2024-02-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_alter_attendance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
